# Generated by Django 4.2.11 on 2024-05-18 12:14

from django.db import migrations
from ..forms import EMPLOYER, JOB_SEEKER

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups = [
        {'name': JOB_SEEKER},
        {'name': EMPLOYER},
    ]

    for group_data in groups:
        Group.objects.get_or_create(**group_data)

def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups = [
        {'name': JOB_SEEKER},
        {'name': EMPLOYER},
    ]

    for group_data in groups:
        Group.objects.filter(**group_data).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
